### ISSUE TITLE
Support Rust 2021

### ISSUE THREAD

**Issue by MolotovCherry** [cherryleafroad/IntelliJ-Rust-Playground#12]
I'd love to do it, but I'm waiting for the [cargo play author to accept my pull request](https://github.com/fanzeyi/cargo-play/pull/70). All we can do is wait! 😢

**Comment by yerke** [comment]
While you wait, you potentially could fork cargo-play and point your plugin to it. Just an option.

**Comment by MolotovCherry** [comment]
I'd have to upload it to crates.io. Even though it's a trivial change in my plugin, I can't justify uploading a new duplicate crate just to work around the issues, then delete it after the pull request gets accepted.

(Also, unrelated, but my computer is broken, so I can't really do any work on this anymore anyways)

Edit: does seem like there's a --git option for cargo install, but sadly my broken computer is the major issue right now

**Comment by yerke** [comment]
Your plugin worked great after I installed your fork of `cargo-play` with `cargo install --git https://github.com/cherryleafroad/cargo-play.git`. Thank you very much for making it. I hope you will be able to fix your computer soon.

**Comment by MolotovCherry** [comment]
> Your plugin worked great after I installed your fork of `cargo-play` with `cargo install --git https://github.com/cherryleafroad/cargo-play.git`. Thank you very much for making it. I hope you will be able to fix your computer soon.

I'm glad to hear that! I hope to get the plugin updated to 2021 edition soon too.

**Comment by MolotovCherry** [comment]
The developer has finally merged the pull request. Now what's left to do here is add the enums to the plugin (once he does a full release)

**Comment by MolotovCherry** [comment]
Compatibility updates finished and working, along with the new 2021 edition switch. 2.1.4 update released (takes a few days to verify before release).

If you'd like early access to the update, here it is
[Rust Playground-2.1.4-stable.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/8187158/Rust.Playground-2.1.4-stable.zip)
