### ISSUE TITLE
Not compatable with Goland version 

### ISSUE THREAD

**Issue by Dabnis** [cherryleafroad/IntelliJ-Rust-Playground#13]
Not compatible with latest Goland update: Build #GO-221.5080.224, built on April 13, 2022

**Comment by MolotovCherry** [comment]
I just ran a compatibility test against your stated version using the official tool, and it stated no problems. Can you provide more info about what's happening on your end?

Can you provide some of the following?
Steps to reproduce
Screenshots
A detailed description of what's happening
Errors and exactly what they are if you are receiving them

Because from what I can see here from the report, there is no problem

![image](https://user-images.githubusercontent.com/13651622/164043474-108855db-c0a3-426f-a63e-15c43db53560.png)

**Comment by Dabnis** [comment]
Thanks for the quick response.

I have attached a screen shot of the Golang Plugins dialog that shows the issue after I recently updated to the newest version of Golang.

Regards.
Jonathan

**Comment by MolotovCherry** [comment]
It seems that Github strips attachments when sent from email. The attachment didn't make its way through

**Comment by Dabnis** [comment]
![Capture1](https://user-images.githubusercontent.com/500683/164045043-17da3afc-5b8d-4961-9c69-b3c059ff3cd7.PNG)

**Comment by Dabnis** [comment]
![Capture](https://user-images.githubusercontent.com/500683/164045513-f4e0e51f-1cad-4c5c-8ec8-40bd8ddf427e.PNG)

**Comment by Dabnis** [comment]
Have just uninstalled the plugin, and now it no longer appears in the marketplace for selection!

**Comment by MolotovCherry** [comment]
Yeah, it's not too big of a deal. IntelliJ probably updated the version code. Just requires 1 number change and it's all good. It's gonna be like this every major update of theirs, cause I can never confirm if it's actually compatible first (although as you can see by the test I ran, it is, so a version bump is all that's needed)

**Comment by cherryleafroad** [comment]
I'm afraid updating the plugin might not be possible at the moment due to an JetBrains product bug which prevents building on 221 targets.
https://youtrack.jetbrains.com/issue/IDEA-292389

I have no choice but to wait for them to fix it

**Comment by Dabnis** [comment]
That's fine, just wanted to bring the bug to your attention.

I will track that JetBrains issue

**Comment by MolotovCherry** [comment]
Actually, seems there's a fix to that one too. Please try this build and confirm it works fine for you (if so, you can close this issue); also, feel free to keep it until the official update rolls out. After your confirmation, I'll push it to the store

[Rust Playground-2.1.5-stable.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/8515304/Rust.Playground-2.1.5-stable.zip)

**Comment by MolotovCherry** [comment]
Okay, I pushed it to the market. It'll take a maximum 2 days to show up (you can use the above zip if you want it sooner)
