### ISSUE TITLE
Playground requires cargo-play binary crate

### ISSUE THREAD

**Issue by Ziggizag** [cherryleafroad/IntelliJ-Rust-Playground#6]
Event log complains:

"Playground requires cargo-play binary crate" on each and every non-Rust IntelliJ Idea project.

Can this message be disabled for non-Rust projects?

**Comment by MolotovCherry** [comment]
Let me see..

It might be a problem here. From what I can see, toolchain would probably be null on non-Rust projects, therefore always triggering this regardless whether it's installed or not
`val isCargoPlayInstalled = project.toolchain?.hasCargoExecutable("cargo-play") ?: false`

**Comment by MolotovCherry** [comment]
Hi, please test out this version.

Does it fix your problem in non-Rust projects? (Please also test that it works as expected in Rust-only projects)

**Comment by Ziggizag** [comment]
Well - I am a Rust noob - just starting learning but as far as I can see - it works as expected and stopped generating this nasty notice while opening my PHP projects - thank you!

**Comment by MolotovCherry** [comment]
I'm glad to hear that. There was actually a small problem with that one and I updated it with better code again.
Here's the fixed update again while you wait for it to be released

[Rust Playground-1.0.4.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/6832810/Rust.Playground-1.0.4.zip)
