### ISSUE TITLE
Incompatible with CLion 2021.2 IDE

### ISSUE THREAD

**Issue by astrolemonade** [cherryleafroad/IntelliJ-Rust-Playground#8]

**Comment by MolotovCherry** [comment]
Probably compatible, I just need to update the compatible version tags. I'll check it out and verify it works when I have a little time

**Comment by MolotovCherry** [comment]
@cata0309 Can you please test this release to see if it works?
[Rust Playground-1.0.5.zip](https://github.com/cherryleafroad/IntelliJ-Rust-Playground/files/6921175/Rust.Playground-1.0.5.zip)

**Comment by cherryleafroad** [comment]
@cata0309 Waiting for you to test this and verify it works as expected.

**Comment by astrolemonade** [comment]
Yes, I could install it

**Comment by MolotovCherry** [comment]
That's good. An update has been issued to the IntelliJ store. It should be approved in a maximum of 3 days. As far as I can tell, functionality is working properly. Have fun!
